import { defineConfig } from 'vite'
import react from '@vitejs/plugin-react'
import { VitePWA } from 'vite-plugin-pwa'

export default defineConfig({
  plugins: [
    react(),
    VitePWA({
      registerType: 'autoUpdate',
      injectRegister: 'auto',

      // Overwrite the existing site.webmanifest in public/ with the
      // correctly-structured one generated by the plugin at build time.
      manifestFilename: 'site.webmanifest',

      // The scope and base MUST match the nginx-served path.
      scope: '/pmloading/',
      base:  '/pmloading/',

      manifest: {
        name:             'BSP Plate Mill Loading System',
        short_name:       'BSP Loading',
        description:      'Bhilai Steel Plant – Plate Mill Loading Operations',
        theme_color:      '#1b3865',
        background_color: '#eaecf0',
        display:          'standalone',
        orientation:      'any',
        // start_url and scope are resolved relative to base by the plugin.
        start_url:        '/pmloading/',
        scope:            '/pmloading/',
        icons: [
          {
            // Relative paths — the plugin prepends the base automatically.
            src:     'web-app-manifest-192x192.png',
            sizes:   '192x192',
            type:    'image/png',
            // 'any' = regular icon used by browsers/Chrome install prompt.
            purpose: 'any',
          },
          {
            src:     'web-app-manifest-512x512.png',
            sizes:   '512x512',
            type:    'image/png',
            // 'maskable' = Android adaptive icon (safe-area cropping).
            purpose: 'maskable',
          },
          {
            // Provide the 512 as 'any' too so desktop Chrome is happy.
            src:     'web-app-manifest-512x512.png',
            sizes:   '512x512',
            type:    'image/png',
            purpose: 'any',
          },
        ],
      },

      workbox: {
        // Cache all build output (JS, CSS, HTML, images, fonts).
        globPatterns: ['**/*.{js,css,html,ico,png,svg,woff,woff2}'],

        // Serve index.html for any navigation the SW intercepts (SPA routing).
        navigateFallback: '/pmloading/index.html',

        // Never intercept API calls — those must always hit the network.
        navigateFallbackDenylist: [/^\/pmloading\/api\//],

        runtimeCaching: [
          {
            urlPattern: /\/pmloading\/api\//,
            handler:    'NetworkOnly',
          },
        ],

        cleanupOutdatedCaches: true,
      },
    }),
  ],
  base: '/pmloading/',
})