import { defineConfig } from 'vite'
import react from '@vitejs/plugin-react'
import { VitePWA } from 'vite-plugin-pwa'

export default defineConfig({
  plugins: [
    react(),
    VitePWA({
      registerType: 'autoUpdate',
      injectRegister: 'auto',

      // Overwrite the existing site.webmanifest in public/ with the
      // correctly-structured one generated by the plugin at build time.
      manifestFilename: 'site.webmanifest',

      // The scope and base MUST match the nginx-served path.
      scope: '/pmloading/',
      base:  '/pmloading/',

      manifest: {
        name:             'BSP Plate Mill Loading System',
        short_name:       'BSP Loading',
        description:      'Bhilai Steel Plant – Plate Mill Loading Operations',
        theme_color:      '#1b3865',
        background_color: '#eaecf0',
        display:          'standalone',
        orientation:      'any',
        // Stable app identifier — prevents browsers from treating a
        // start_url change as a new/different PWA.
        id:               '/pmloading/',
        // Default text direction for the app's language.
        dir:              'ltr',
        // App store / install-experience categories.
        categories:       ['business', 'productivity'],
        // Display-override sequence — the browser tries each in order
        // before falling back to the `display` member.  window-controls-
        // overlay lets us paint into the title‑bar area on desktop.
        display_override: ['window-controls-overlay', 'standalone'],
        // Single-instance behaviour: navigations to the PWA's scope focus
        // the existing window instead of opening a new one.
        launch_handler:   { client_mode: 'focus-existing' },
        // start_url and scope are resolved relative to base by the plugin.
        start_url:        '/pmloading/',
        scope:            '/pmloading/',
        icons: [
          {
            // Relative paths — the plugin prepends the base automatically.
            src:     'web-app-manifest-192x192.png',
            sizes:   '192x192',
            type:    'image/png',
            // 'any' = regular icon used by browsers/Chrome install prompt.
            purpose: 'any',
          },
          {
            src:     'web-app-manifest-512x512.png',
            sizes:   '512x512',
            type:    'image/png',
            // 'maskable' = Android adaptive icon (safe-area cropping).
            purpose: 'maskable',
          },
          {
            // Provide the 512 as 'any' too so desktop Chrome is happy.
            src:     'web-app-manifest-512x512.png',
            sizes:   '512x512',
            type:    'image/png',
            purpose: 'any',
          },
        ],
        // Screenshots enable Chrome's "Rich Install UI", which shows
        // screenshots and a description in the install dialog.
        screenshots: [
          {
            // Desktop (landscape) — form_factor: 'wide' signals a
            // layout meant for keyboard/mouse use.
            src:          'screenshot-2560x1440.png',
            sizes:        '2560x1440',
            type:         'image/png',
            form_factor:  'wide',
            label:        'BSP Plate Mill Loading System — desktop view',
          },
          {
            // Mobile (portrait) — leaving out form_factor defaults it to
            // "narrow", which is what Chrome expects for phone screenshots.
            src:          'screenshot-Pixel 7.png',
            sizes:        '412x915',
            type:         'image/png',
            label:        'BSP Plate Mill Loading System — mobile view',
          },
          {
            // Tablet (portrait).
            src:          'screenshot-1600x2560.png',
            sizes:        '1600x2560',
            type:         'image/png',
            label:        'BSP Plate Mill Loading System — tablet view',
          },
        ],
      },

      workbox: {
        // Cache all build output (JS, CSS, HTML, images, fonts).
        globPatterns: ['**/*.{js,css,html,ico,png,svg,woff,woff2}'],

        // Serve index.html for any navigation the SW intercepts (SPA routing).
        navigateFallback: '/pmloading/index.html',

        // Never intercept API calls — those must always hit the network.
        navigateFallbackDenylist: [/^\/pmloading\/api\//],

        runtimeCaching: [
          {
            urlPattern: /\/pmloading\/api\//,
            handler:    'NetworkOnly',
          },
        ],

        cleanupOutdatedCaches: true,
      },
    }),
  ],
  base: '/pmloading/',
})