services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: pmload-frontend
    ports:
      - "8705:8705"
    depends_on:
      - backend
    restart: unless-stopped

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: pmload-backend
    ports:
      - "8706:8706"
    restart: unless-stopped
